[package]
name = "wildflower"
description = "WildflowerOS: A WIP operating system for x86_64"
version = "0.1.0"
authors = ["Zander Lewis <zander@zanderlewis.dev>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/zanderlewis/wildflower"
readme = "README.md"
default-run = "wildflower"

[features]
default = ["video"]
video = []
serial = []
userspace = []

[dependencies]
acpi = "5.0.0"
aml = "0.16.4"
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }
bit_field = "0.10.2"
bootloader = { version = "0.9.29", features = ["map_physical_memory"] }
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
libm = "0.2.11"
linked_list_allocator = "0.10.5"
littlewing = { version = "0.7.0", default-features = false }
nom = { version = "8.0.0", default-features = false, features = ["alloc"] }
num-bigint = { version = "0.4.6", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
object = { version = "0.36.7", default-features = false, features = ["read"] }
pbkdf2 = { version = "0.12.2", default-features = false, features = ["hmac"] }
pc-keyboard = "0.8.0"
pic8259 = "0.11.0"
rand = { version = "0.9.0", default-features = false }
rand_hc = "0.4.0"
raw-cpuid = "11.3.0"
sha2 = { version = "0.10.8", default-features = false, features = ["force-soft"] }
smoltcp = { version = "0.12.0", default-features = false, features = ["alloc", "medium-ethernet", "socket-tcp", "socket-udp", "socket-dhcpv4", "proto-ipv4", "proto-dhcpv4"] }
spin = "0.10.0"
time = { version = "0.3.37", default-features = false }
geodate = { version = "0.5.0", default-features = false }
uart_16550 = "0.3.2"
vte = "0.13.1"
x86_64 = "0.15.2"

[package.metadata.bootloader]
physical-memory-offset = "0xFFFF800000000000"
kernel-stack-address   = "0xFFFFFF8000000000"
boot-info-address      = "0xFFFFFFFF80000000"

[package.metadata.bootimage]
test-success-exit-code = 33 # (0x10 << 1) | 1
